#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

canCompile || exit 0    # Dynamic code

mkdir 0

restore0Dir

runApplication blockMesh 

##runApplication mirrorMesh

##runApplication -o decomposePar -force 

runApplication pimpleFoam

##runApplication reconstructPar

#foamToVTK

touch ff.foam

##runApplication $(getApplication) 

##runApplication postProcess -func streamFunction

#------------------------------------------------------------------------------
